<div>
    <div class="survey-section">
        <h1>Survey Builder</h1>
    </div>
    <div class="survey-section">
        <form>
            <label for="survey-name">Survey Name</label>
            <input type="text" id="survey-name" name="survey-name">
        </form>
    </div>
</div>
<div id="survey-section">
    <div id="survey-questions">
    <h3>Questions</h3>
        <form>
            <label for="swallow">Is that an African of European swallow?</label><br>
            <input type="radio" name="swallow" value="African">African<br>
            <input type="radio" name="swallow" value="European">European<br>
            <input type="button" value="Remove">
        </form>
        <form>
            <label for="cheese">Do you like cheese?</label><br>
            <input type="text" name="cheese" placeholder="Tell me how much:"><br>
            <input type="button" value="Remove">
        </form>
        <form>
            <label for="colour">Select which colours you like:</label><br>
            <input type="checkbox" name="colour" value="Blue">Blue<br>
            <input type="checkbox" name="colour" value="Light Blue">Light Blue<br>
            <input type="button" value="Remove">
        </form>
    </div>
</div>
<div class="survey-section question-adder">
    <label for="question">Question</label>
    <input type="text" id="question" name="question">
    <label for="question-type">Type</label>
    <select id="input-selector">
        <option value="text-input" selected>Text</option>
        <option value="radio-input">Radio</option>
        <option value="checkbox-input">Checkbox</option>
    </select>
    <label for="required">Required?</label>
    <input type="checkbox" id="required" name="required">
    <input id="add-question" type="submit" value="Add">
</div>
<div class="survey-section">
    <button id="cancel-btn" class="btn btn-danger">Cancel</button>
    <input id="submit-btn" class="btn btn-success" type="submit" value="Save Survey">
</div>