<div>
    <div class="survey-section">
        <h1>Survey Builder</h1>
    </div>
    <div class="survey-section">
        <form>
            <label for="survey-name">Survey Name</label>
            <input type="text" id="survey-name" name="survey-name">
        </form>
    </div>
</div>
<div id="survey-section">
    <h3>Questions</h3>
</div>
<div class="survey-section question-adder">
    <form>
        <label for="question">Question</label>
        <input type="text" id="question" name="question">
        <label for="question-type">Type</label>
        <select id="input-selector">
            <option class="text-input">Text</option>
            <option class="radio-input">Radio</option>
            <option class="checkbox-input">Checkbox</option>
        </select>
        <label for="required">Required?</label>
        <input type="checkbox" id="required" name="required">
        <input id="add-question" type="submit" value="Add">
    </form>
</div>
<div class="survey-section">
    <button id="cancel-btn" class="btn btn-danger">Cancel</button>
    <input id="submit-btn" class="btn btn-success" type="submit" value="Save Survey">
</div>