<div class="container">
    <div class="row">
        <div class="col-md-offset-5 col-md-3">
            <div class="form-login">
                <form method="post" action="account">
                    <h4>Welcome back, amigos!</h4>
                    <input type="text" name="email" id="userName" class="form-control input-sm chat-input" placeholder="e-mail" />
                    </br>
                    <input type="password" name="password" id="userPassword" class="form-control input-sm chat-input" placeholder="password" />
                    </br>
                    <div class="wrapper">
                <span class="group-btn">
                    <input type="submit" value="Login" class="btn btn-success btn-md"><i class="fa fa-sign-in"></i></input>
                </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>